# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WeatherTracker(object):
    def setupUi(self, WeatherTracker):
        WeatherTracker.setObjectName("WeatherTracker")
        WeatherTracker.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        WeatherTracker.resize(755, 605)
        WeatherTracker.setStyleSheet("QMainWindow {\n"
"    border-radius: 15px;\n"
"    background-color: #ffffff;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=WeatherTracker)
        self.centralwidget.setStyleSheet("QWidget {\n"
"    border-radius: 15px;\n"
"    background-color: #737feb;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.gridFrame.setGeometry(QtCore.QRect(10, 50, 341, 551))
        self.gridFrame.setObjectName("gridFrame")
        self.Temp = QtWidgets.QLabel(parent=self.gridFrame)
        self.Temp.setGeometry(QtCore.QRect(90, 340, 211, 171))
        self.Temp.setStyleSheet("QLabel {\n"
"    border-radius: 15px;\n"
"    background-color: #98a1f5;\n"
"    font-size: 140px;\n"
"\n"
"    text-align: left;\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"    color: white;\n"
"}")
        self.Temp.setText("")
        self.Temp.setObjectName("Temp")
        self.iconWeather = QtWidgets.QLabel(parent=self.gridFrame)
        self.iconWeather.setGeometry(QtCore.QRect(40, 10, 271, 261))
        self.iconWeather.setText("")
        self.iconWeather.setObjectName("iconWeather")
        self.verticalFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.verticalFrame.setGeometry(QtCore.QRect(0, 10, 751, 41))
        self.verticalFrame.setObjectName("verticalFrame")
        self.CityBox = QtWidgets.QComboBox(parent=self.verticalFrame)
        self.CityBox.setGeometry(QtCore.QRect(300, 0, 154, 41))
        self.CityBox.setStyleSheet("QComboBox {\n"
"    background-color: #98a1f5;\n"
"    border: 1px solid #4a5568;\n"
"    border-radius: 6px;\n"
"    padding: 8px 15px;\n"
"    color: #0c0c0d;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border-left: 0px solid #0c0c0d;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    border-top: 4px solid #0c0c0d;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #white;\n"
"    border: 1px solid #4a5568;\n"
"    border-radius: 6px;\n"
"    outline: 0px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item {\n"
"    background-color: #3d4163;\n"
"    border: 0px;\n"
"    border-radius: 6px;\n"
"    color: white;\n"
"}")
        self.CityBox.setObjectName("CityBox")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(380, 60, 361, 541))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.otherStat = QtWidgets.QLabel(parent=self.frame)
        self.otherStat.setGeometry(QtCore.QRect(50, 0, 281, 461))
        self.otherStat.setStyleSheet("QLabel {\n"
"    border-radius: 15px;\n"
"    background-color: #98a1f5;\n"
"    border: 1px solid #020203;\n"
"    font-size: 17px;\n"
"    color: #25252b;\n"
"        \n"
"\n"
"    text-align: left;\n"
"    padding: 0px;                   \n"
"    margin: 0px;\n"
"}")
        self.otherStat.setText("")
        self.otherStat.setObjectName("otherStat")
        WeatherTracker.setCentralWidget(self.centralwidget)

        self.retranslateUi(WeatherTracker)
        QtCore.QMetaObject.connectSlotsByName(WeatherTracker)

    def retranslateUi(self, WeatherTracker):
        _translate = QtCore.QCoreApplication.translate
        WeatherTracker.setWindowTitle(_translate("WeatherTracker", "MainWindow"))
